name: GitHub Pages Deploy

on:
  push:
    branch:
      - master


jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]
    
    env:
      SHEET_KEYS: ${{ secrets.SHEET_KEYS }}
      GITHUB_TOKEN: ${{ secrets.DEPLOY_KEY_GITHUB_PAGE }}
      DEPLOY_USER_NAME: Bingluen
      DEPLOY_USER_EMAIL: bingluen0224@gmail.com
      PUBLISH_DIR: ./dist
    
    steps:
      - uses: actions/checkout@v2 
      - name: Install Dependencies
        run: npm install
      - name: Building static page
        run: npm run generate
      - name: Deploy to Github Pages
        run: |
          cd $PUBLISH_DIR
          git init
          git config --local user.email $DEPLOY_USER_EMAIL
          git config --local user.name $DEPLOY_USER_NAME
          git remote add origin https://$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git
          git checkout -b gh-pages
          echo -n "ray2020.pdis.dev" > CNAME
          git add --all
          git commit -m "Deploy $GITHUB_SHA to GitHub Pages"
          git push origin gh-pages -f
        


